apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bind9-helm.fullname" . }}-config
  labels:
    {{- include "bind9-helm.labels" . | nindent 4 }}
data:
  named.conf: |
    options {
      directory "/var/cache/bind";

      dnssec-enable yes;
      dnssec-validation yes;

      auth-nxdomain no;

      listen-on port 53 { any; };
      listen-on-v6 { any; };

      recursion yes;
      allow-query { any; };
      allow-query-cache { any; };

      forward only;
      forwarders {
    {{- range .Values.forwarders }}
        {{ . }};
    {{- end }}
      };

      empty-zones-enable no;
      querylog yes;
      version "latest";
    };

    {{- if .Values.zones }}
    {{- range .Values.zones }}
    zone "{{ .name }}" {
      type forward;
      forward only;
      forwarders {
    {{- range .forwarders }}
        {{ . }};
    {{- end }}
      };
    };
    {{- end }}
    {{- end }}
