apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bind9-helm.fullname" . }}-config
  labels:
    {{- include "bind9-helm.labels" . | nindent 4 }}
data:
  named.conf: |
    acl "trusted" {
    {{- range .Values.trusted }}
        {{ . }};
    {{- end }}
    };

    options {
      directory "/var/cache/bind";

      auth-nxdomain no;
      dnssec-validation auto;
      empty-zones-enable no;
      querylog yes;
      version "not available";
      recursion yes;

      allow-query { any; };
      allow-recursion { trusted; };
      allow-query-cache { trusted; };

      forwarders {
    {{- range .Values.forwarders }}
        {{ . }};
    {{- end }}
      };
      forward only;
    };

    {{- if .Values.zones }}
    {{- range .Values.zones }}
    zone "{{ .name }}" {
      type forward;
      forward only;
      forwarders {
    {{- range .forwarders }}
        {{ . }};
    {{- end }}
      };
    };
    {{- end }}
    {{- end }}
