apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bind9-helm.fullname" . }}
  labels:
    {{- include "bind9-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bind9-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bind9-helm.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "bind9-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: dns-tcp
          readinessProbe:
            tcpSocket:
              port: dns-tcp
          volumeMounts:
            - name: "{{ template "bind9-helm.fullname" . }}-config"
              mountPath: "/etc/bind"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: "{{ template "bind9-helm.fullname" . }}-config"
          configMap:
            name: "{{ template "bind9-helm.fullname" . }}-config"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
